(()=>{const cards=window.CARDS||[],practice=window.PRACTICE||[];const sections=[...new Set(cards.map(x=>x.section))];const root=document.getElementById("sections"),nav=document.getElementById("nav"),search=document.getElementById("search");const key="qa-cheatsheet-done-v2";let done=new Set(JSON.parse(localStorage.getItem(key)||"[]"));let focus=false,answersHidden=false;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function idFor(s){return"sec-"+s.toLowerCase().replace(/[^a-zа-я0-9]+/gi,"-").replace(/(^-|-$)/g,"")}
function cardId(x,i){return btoa(unescape(encodeURIComponent(x.section+"|"+x.q))).replace(/=+/g,"").slice(0,24)+"-"+i}
function render(){root.innerHTML="";nav.innerHTML="";
sections.forEach(section=>{const id=idFor(section),items=cards.filter(x=>x.section===section);const nb=document.createElement("button");nb.textContent=section+" ("+items.length+")";nb.onclick=()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});nav.appendChild(nb);
const sec=document.createElement("section");sec.className="section";sec.id=id;sec.innerHTML='<div class="sectionhead"><div><h2>'+esc(section)+'</h2><p><span class="count">'+items.length+' карточек</span></p></div></div><div class="grid"></div>';const grid=sec.querySelector(".grid");
items.forEach((x,localIdx)=>{const globalIdx=cards.indexOf(x),cid=cardId(x,globalIdx),c=document.createElement("article");c.className="card"+(x.must?" must":"");c.dataset.search=(x.section+" "+x.q+" "+x.a).toLowerCase();c.dataset.must=x.must?"1":"0";
let tags=(x.must?'<span class="tag must">★ MUST KNOW</span>':"")+(x.pdf?'<span class="tag pdf">PDF-вопрос</span>':"")+(x.level==="deep"?'<span class="tag deep">Deep</span>':"");
c.innerHTML='<div class="meta">'+tags+'</div><h3>'+esc(x.q)+'</h3><div class="answer">'+esc(x.a)+'</div><div class="actions"><button class="mini reveal">Скрыть/показать ответ</button><button class="mini done '+(done.has(cid)?"on":"")+'" data-id="'+cid+'">'+(done.has(cid)?"✓ Знаю":"Отметить «знаю»")+'</button></div>';
grid.appendChild(c)});root.appendChild(sec)});
bind();updateProgress();applyFilters();observe()}
function bind(){document.querySelectorAll(".reveal").forEach(b=>b.onclick=()=>{const a=b.closest(".card").querySelector(".answer");a.hidden=!a.hidden});document.querySelectorAll(".done").forEach(b=>b.onclick=()=>{const id=b.dataset.id;if(done.has(id))done.delete(id);else done.add(id);localStorage.setItem(key,JSON.stringify([...done]));b.classList.toggle("on",done.has(id));b.textContent=done.has(id)?"✓ Знаю":"Отметить «знаю»";updateProgress()})}
function updateProgress(){const n=cards.reduce((sum,x,i)=>sum+(done.has(cardId(x,i))?1:0),0);document.getElementById("progressText").textContent=n+" / "+cards.length;document.getElementById("progressBar").style.width=(cards.length?n/cards.length*100:0)+"%"}
function applyFilters(){const q=search.value.trim().toLowerCase();document.querySelectorAll("#sections .card").forEach(c=>{const show=(!focus||c.dataset.must==="1")&&(!q||c.dataset.search.includes(q));c.classList.toggle("hide",!show)});document.querySelectorAll("#sections .section").forEach(s=>{const visible=[...s.querySelectorAll(".card")].some(c=>!c.classList.contains("hide"));s.classList.toggle("hide",!visible)})}
search.addEventListener("input",applyFilters);document.getElementById("focusBtn").onclick=e=>{focus=!focus;e.currentTarget.textContent=focus?"✓ Только Must know":"⚡ 15 минут";e.currentTarget.classList.toggle("primary",focus);applyFilters()};
document.getElementById("answersBtn").onclick=e=>{answersHidden=!answersHidden;document.body.classList.toggle("answers-off",answersHidden);e.currentTarget.textContent=answersHidden?"Показать ответы":"Скрыть ответы"};
function drawPractice(){const p=document.getElementById("practiceList");p.innerHTML="";practice.forEach((x,i)=>{const d=document.createElement("article");d.className="practice";d.innerHTML='<div class="meta"><span class="tag pdf">PDF mini-practice</span><span class="tag">'+esc(x.src)+'</span></div><h3>'+esc(x.title)+'</h3><pre class="code">'+esc(x.code)+'</pre><div class="options">'+x.options.map((o,j)=>'<div class="option">'+(j+1)+") "+esc(o)+'</div>').join("")+'</div><button class="btn showSolution">Показать разбор</button><div class="solution"><b>Ответ: '+esc(x.answer)+'</b><br>'+esc(x.why)+'</div>';d.querySelector(".showSolution").onclick=()=>d.querySelector(".solution").classList.toggle("show");p.appendChild(d)})}
function nextQuestion(){const pool=focus?cards.filter(x=>x.must):cards;const x=pool[Math.floor(Math.random()*pool.length)];document.getElementById("qTopic").textContent=x.section;document.getElementById("qText").textContent=x.q;document.getElementById("qAnswer").textContent=x.a;document.getElementById("qAnswer").classList.remove("show")}
document.getElementById("nextQuestion").onclick=nextQuestion;document.getElementById("showAnswer").onclick=()=>document.getElementById("qAnswer").classList.toggle("show");document.getElementById("randomBtn").onclick=()=>{document.getElementById("interview").scrollIntoView({behavior:"smooth"});nextQuestion()};
function observe(){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.textContent.startsWith(e.target.querySelector("h2")?.textContent||"§§§")))}}),{rootMargin:"-80px 0px -70% 0px"});document.querySelectorAll("#sections .section").forEach(s=>obs.observe(s))}
drawPractice();render();nextQuestion()})();