window.CARDS=(window.CARDS||[]).concat([
{section:"POS / Desktop",q:"Как бы вы тестировали кассовый стенд end-to-end?",a:"Собрать карту компонентов: кассовое приложение, backend/API, БД, платежный терминал, сканер, принтер, весы/дисплей и сеть. Проверить happy path продажи, скидки/налоги, разные оплаты, отмену/возврат, offline/reconnect, сбои периферии, перезапуск, обновление версии и восстановление данных.",must:1},
{section:"POS / Desktop",q:"Что важно при приемке новой версии кассового ПО?",a:"Проверить install/upgrade/rollback, миграции конфигураций/БД, критический smoke, исправленные дефекты, затронутую регрессию, совместимость с оборудованием, логирование, работу после reboot и сценарии восстановления после частичного сбоя.",must:1},
{section:"POS / Desktop",q:"Как воспроизвести дефект с клиентского кассового узла?",a:"Зафиксировать точные версии ПО/ОС/драйверов/прошивок и конфигурацию, забрать логи и timestamps, тестовые данные и шаги, собрать максимально близкий стенд, сначала воспроизвести минимальный сценарий, затем варьировать по одному фактору.",must:1},
{section:"POS / Desktop",q:"Какие риски специфичны для кассового ПО?",a:"Потеря/дублирование транзакции, неверная сумма/налог/скидка, рассинхронизация online/offline, неверная печать чека, отказ периферии, зависание UI во время оплаты, повторная отправка команды, несовместимость драйверов и некорректное обновление.",must:1},
{section:"POS / Desktop",q:"Почему Selenium не подходит для нативного desktop GUI?",a:"Selenium WebDriver автоматизирует браузеры и DOM. Для native Windows UI применяют Windows UI Automation-совместимые инструменты, например FlaUI/Appium Windows/другие драйверы конкретного стека. Если приложение содержит WebView, его web-часть может тестироваться Selenium.",must:1},
{section:"POS / Desktop",q:"Как строить устойчивые desktop GUI автотесты?",a:"Использовать стабильные automation IDs/accessibility properties, ожидания состояния вместо sleep, изоляцию тестовых данных, управляемый lifecycle приложения, recovery после crash, screenshots/logs/video и abstraction layer для экранов/контролов.",must:1},
{section:"POS / Desktop",q:"Что делать, если касса работает на нестандартном железе?",a:"Вести матрицу совместимости OS × driver × firmware × device model, фиксировать эталонные конфиги, разделять дефекты ПО/драйвера/железа, проверять USB/COM/network connectivity и иметь диагностический checklist с логами и командами.",must:1},
{section:"POS / Desktop",q:"Как взаимодействовать с вендором оборудования по дефекту?",a:"Передать воспроизводимый кейс: модель/серийная ревизия, firmware/driver, OS, схема подключения, timestamps, raw logs/trace, ожидаемое и фактическое, минимальный сценарий и доказательство, где проходит граница ответственности.",must:1},

{section:"Bug reports / Jira",q:"Что должно быть в информативном bug report?",a:"Короткий однозначный title, environment/build, preconditions, steps, actual vs expected, reproducibility, severity/priority по процессу, attachments: logs/screens/video/request-response, а для интеграций — correlation/request IDs и timestamps.",must:1},
{section:"Bug reports / Jira",q:"Severity vs Priority?",a:"Severity — техническое/бизнес-влияние дефекта; Priority — насколько быстро его нужно исправить. Критичный баг обычно высокий по обоим, но возможны комбинации: косметика на главном экране может иметь high priority при low severity.",must:1},
{section:"Bug reports / Jira",q:"Как донести сложную техническую проблему разработчику?",a:"Начать с симптома и impact, затем дать краткий воспроизводимый сценарий, факты из логов/метрик, границы воспроизведения и гипотезы отделить от доказанных фактов. Не подменять диагностику обвинением конкретного компонента.",must:1},
{section:"Bug reports / Jira",q:"Что полезно хранить в Confluence?",a:"Инструкции install/configuration, troubleshooting decision trees, матрицы совместимости, test strategy/checklists, release notes, known issues, схемы стенда/сети и runbooks. Документ должен иметь owner и дату актуальности."},

{section:"Linux / Windows",q:"Какие Linux-команды нужны QA инженеру кассовых стендов?",a:"ps/top, systemctl/journalctl, grep/tail/less, find, ls/cp/mv/chmod/chown, df/du/free, ip/ss, ping/traceroute, curl, dig/nslookup, lsof, dmesg, uname, env. На интервью объясняйте, что диагностируете каждой командой.",must:1},
{section:"Linux / Windows",q:"Как посмотреть логи сервиса Linux?",a:"Для systemd: journalctl -u service --since '10 min ago' и systemctl status service. Для файловых логов: tail -f, grep по timestamp/error/correlation id. Всегда сверять timezone.",must:1},
{section:"Linux / Windows",q:"Процесс не стартует. Ваш алгоритм?",a:"Проверить exit code/status, logs, конфиг и environment variables, права/пользователя, занятый порт, зависимости/БД/сеть, диск/RAM, версии runtime/библиотек. Затем минимизировать изменение, которое вернет сервис в рабочее состояние.",must:1},
{section:"Linux / Windows",q:"Что проверить в Windows при проблеме desktop приложения?",a:"Event Viewer, Services, Task Manager/Process Explorer, права пользователя/UAC, environment variables, firewall, порты, драйверы/Device Manager, установленные runtime, логи приложения, пути/registry только если они реально используются продуктом.",must:1},
{section:"Linux / Windows",q:"Как отличить проблему приложения от ОС/драйвера?",a:"Сравнить на эталонном стенде, заменить один слой за раз, проверить устройство штатной утилитой/driver diagnostics, подтвердить raw OS-level error и воспроизводимость вне приложения. Не делать вывод только по месту появления симптома."},

{section:"Networks",q:"Что происходит при обращении клиента к https://host:443?",a:"DNS разрешает имя в IP, выбирается маршрут, TCP устанавливает соединение, затем TLS согласует защищенный канал, после чего идет HTTP. На каждом слое свои симптомы и инструменты диагностики.",must:1},
{section:"Networks",q:"IP, subnet mask, gateway — что это?",a:"IP идентифицирует интерфейс, mask/prefix определяет локальную сеть, default gateway используется для адресов вне локального subnet. Ошибка в любом из трех может сделать узел недоступным.",must:1},
{section:"Networks",q:"TCP vs UDP?",a:"TCP — connection-oriented, надежная упорядоченная byte stream с retransmission; UDP — datagrams без гарантии доставки/порядка и с меньшим protocol overhead. Выбор зависит от протокола приложения.",must:1},
{section:"Networks",q:"Как проверить, доступен ли порт сервиса?",a:"На Linux ss -lntp для локального listener, nc -vz host port или curl для HTTP; на Windows Test-NetConnection host -Port N. Ping проверяет ICMP и не доказывает доступность TCP-порта.",must:1},
{section:"Networks",q:"Что такое localhost, 127.0.0.1 и 0.0.0.0?",a:"127.0.0.1 — loopback IPv4 адрес локального хоста; localhost обычно резолвится в loopback; bind на 0.0.0.0 означает слушать на всех IPv4 interfaces, но это не адрес назначения для удаленного клиента."},

{section:"Git",q:"git fetch vs git pull?",a:"fetch загружает refs/objects и не интегрирует изменения в текущую ветку. pull обычно делает fetch + merge или rebase согласно настройке/флагам.",must:1},
{section:"Git",q:"merge vs rebase?",a:"merge создает/сохраняет ветвящуюся историю и merge commit при необходимости. rebase переигрывает commits на новой базе и переписывает их SHA. Не rebase-ить опубликованную общую историю без договоренности.",must:1},
{section:"Git",q:"reset vs revert?",a:"reset двигает ref и может менять index/worktree; удобен локально, но переписывает историю. revert создает новый commit, отменяющий изменения, поэтому безопаснее для общей ветки.",must:1},
{section:"Git",q:"Что делает git stash?",a:"Временно убирает незакоммиченные изменения из worktree/index в stash, чтобы переключить контекст. Это не замена нормальным commits для долгого хранения работы."},
{section:"Git",q:"Как разрешать merge conflict?",a:"Понять обе стороны, вручную собрать корректный итог, удалить conflict markers, прогнать tests/lint, git add и завершить merge/rebase. Нельзя выбирать ours/theirs без понимания смысла."},

{section:"Kafka",q:"Что такое topic, partition и offset?",a:"Topic — логический поток записей; partition — упорядоченный append-only log и единица параллелизма; offset — позиция записи внутри partition.",must:1},
{section:"Kafka",q:"Где Kafka гарантирует порядок?",a:"Порядок гарантируется внутри одной partition, не по всему topic. Если события одного entity должны быть упорядочены, producer обычно использует стабильный key, чтобы они попадали в одну partition.",must:1},
{section:"Kafka",q:"Что такое consumer group?",a:"Набор consumers, совместно читающих topic: каждая partition назначается максимум одному consumer внутри конкретной group. Другие groups получают свой независимый поток.",must:1},
{section:"Kafka",q:"Почему consumers может быть больше, чем partitions?",a:"Может, но лишние consumers в одной group будут idle, потому что одну partition нельзя одновременно назначить двум consumers той же group.",must:1},
{section:"Kafka",q:"Почему сообщение может обработаться дважды?",a:"При at-least-once consumer может выполнить side effect, но не успеть зафиксировать offset до crash/rebalance. После restart запись придет снова. Поэтому handler/side effects часто проектируют идемпотентными.",must:1},
{section:"Kafka",q:"At-most-once, at-least-once, exactly-once — смысл?",a:"At-most-once допускает потерю, но избегает повторной обработки; at-least-once не теряет подтвержденные записи ценой возможных дублей; exactly-once требует более сильной транзакционной семантики и ограничений end-to-end.",level:"deep"},

{section:"ML",q:"Train / validation / test — зачем разделять?",a:"Train используется для обучения параметров; validation — для выбора гиперпараметров/модели; test — финальная независимая оценка. Утечка test в обучение делает метрику оптимистичной.",must:1},
{section:"ML",q:"Overfitting vs underfitting?",a:"Overfitting: модель слишком подстроилась под train и плохо обобщает. Underfitting: модель недостаточно выражает закономерность и плохо работает даже на train. Смотрят на train/validation curves.",must:1},
{section:"ML",q:"Precision vs Recall?",a:"Precision отвечает: среди предсказанных positive сколько верных; Recall: среди реальных positive сколько нашли. Выбор зависит от стоимости false positive и false negative.",must:1},
{section:"ML",q:"Что такое F1?",a:"Гармоническое среднее precision и recall; полезно как единая метрика при необходимости баланса, но может скрывать разную стоимость ошибок.",must:1},
{section:"ML",q:"Что такое inference?",a:"Применение уже обученной модели к новым данным для получения prediction/output, в отличие от training, где параметры модели оптимизируются."},

{section:"LLM",q:"Что такое token и context window?",a:"Token — единица, на которую tokenizer разбивает input/output. Context window — максимальный объем tokens, доступный модели в одном контексте; туда входят инструкции, история, retrieved data и генерируемый ответ.",must:1},
{section:"LLM",q:"Что делает attention?",a:"Механизм Transformer, который вычисляет, каким элементам контекста уделить вес при построении representation текущего token. Это не «память» в бытовом смысле.",must:1},
{section:"LLM",q:"RAG vs fine-tuning?",a:"RAG подмешивает найденные внешние знания в контекст во время запроса; fine-tuning изменяет параметры/поведение модели обучением. Для быстро меняющейся базы знаний RAG часто практичнее.",must:1},
{section:"LLM",q:"Что такое hallucination и как снижать риск?",a:"Правдоподобный, но неверный/неподтвержденный output. Меры: надежный контекст/RAG, structured outputs, tool calls, явные правила «не знаю», валидация, citations и human review для high-stakes сценариев.",must:1},
{section:"LLM",q:"Temperature — что меняет?",a:"Управляет случайностью sampling распределения следующего token: ниже — более детерминированно, выше — больше разнообразия. Это не коэффициент «умности» модели."},
{section:"LLM",q:"Как тестировать LLM-функцию?",a:"Разделить deterministic оболочку и probabilistic model behavior; собрать versioned eval set, проверять task success, factuality/grounding, schema, safety, latency/cost, regressions; использовать несколько прогонов там, где output вариативен.",must:1}
]);